spring:
  application:
    name: community

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none # validate  INT UNSIGNED + Long 조합 사용
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB      # 파일 하나당 최대 크기
      max-request-size: 5MB   # 요청 전체 최대 크기

  # 타임리프 설정
  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    static-path-pattern: /**

  thymeleaf:
    cache: false  # 개발 중에는 false (배포 시 true로 변경)
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
#    org.springframework.security: debug

# JWT 설정 추가
#jwt:
#  secret: ${JWT_SECRET}
#  access-token-validity: 3600000  # 1시간 (밀리초) - 임시
#  refresh-token-validity: 604800000  # 7일 (밀리초) - 임시

# 파일 저장 경로
file:
  temp-dir: uploads/temp      # 임시 디렉토리 (24시간 후 자동 삭제)
  upload-dir: uploads/images  # 정식 디렉토리 (영구 보관)
  max-size: 5242880           # 5MB (바이트)

# 스케줄러 설정
scheduler:
  view-count-sync:
    enabled: true
    fixed-delay: 30000  # 30초 (밀리초)

# 세션 설정
server:
  servlet:
    session:
      timeout: 3600  # 1시간 (초 단위)
      cookie:
        name: JSESSIONID
        http-only: true  # XSS 방어
        secure: false    # 개발 환경에서는 false (프로덕션에서는 true - HTTPS 필수)
        same-site: lax   # CSRF 방어
